version: '2'
services:
  seatallotment-app:
    image: seatallotment
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_CASSANDRA_CONTACTPOINTS=seatallotment-cassandra
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  seatallotment-cassandra:
    extends:
      file: cassandra-cluster.yml
      service: seatallotment-cassandra
  seatallotment-cassandra-node:
    image: cassandra:3.11.4
    environment:
      - CASSANDRA_SEEDS=seatallotment-cassandra
  seatallotment-cassandra-migration:
    extends:
      file: cassandra-migration.yml
      service: seatallotment-cassandra-migration
    environment:
      - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
